[package]
name = "pepl"
version = "0.0.7"
edition = "2021"
repository = "https://github.com/Kaenigsion/PEPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.82"